[book]
authors = ["dr-frmr", "jtneev", "hosted-fornet", "bitful-pannul", "willbach", "0x70b1a5", "habsul-rignyr", "commercium-sys", "tadad"]
language = "en"
multilingual = false
src = "src"
title = "Kinode Book"

[output.html]
additional-js = ["theme/customize-buttons.js"]
additional-css = ["theme/fonts/custom-fonts.css", "theme/css/variables.css", "theme/css/highlight.css"]
edit-url-template = "https://github.com/uqbar-dao/kinode-book/edit/main/{path}"
