[book]
authors = ["dr-frmr"]
language = "en"
multilingual = false
src = "src"
title = "Nectar Book"

[output.html]
additional-js = ["theme/customize-buttons.js"]
additional-css = ["theme/fonts/custom-fonts.css"]
